### PR TITLE
Fix url in Readme

### PR DESCRIPTION
**Pull request by oxenfree**
Fixed url to http://go.aopphp.com/docs/

### CODE REVIEW

**Comment by lisachenko** [comment]
Hi! ) We are currently configuring new repo for the docs, so please be patient while work in progress. BTW, thank you for pushing this PR!

**Comment by lisachenko** [comment]
@TheCelavi would you like to merge this PR? :)

**Comment by oxenfree** [comment]
> We are currently configuring new repo for the docs, so please be patient while work in progress...thank you for pushing

Hi, not a problem. Was just browsing and thought I could help with a quick fix. 

Thanks!

**Comment by TheCelavi** [comment]
@oxenfree At this moment, we are working on new documentation, to be honest, we are not even sure how deployment model is going to go in real life, but our intention is to:

1. improve and expand documentation as much as possible, with general AOP theory and practice and Go! AOP specific implementation details
2. improve deployment model of docs which will follow release path of framework and related projects

In that matter, I will merge this, but I can not promise that that URL will be kept in the future when docs are really released. 

However, we really want to stress out that any help is very welcome! Feel free to submit any article, paragraph that you believe that it will be useful for other users. Neither Alexander nor I are not native english speaker - just contribution in terms of correcting sentences and grammar in documentation is a huge help.

**Comment by oxenfree** [comment]
Yeah, please let me know when you get new documentation up. I'll go through, do a grammar / spelling edit and make a PR. I was a professional writer / editor. It's quick and easy for me. 

I'd love to help. Just alert me when you're ready. 

Thanks!

**Pull request merged**
